// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApi.Models;

public partial class DetallesEnvio
{
    public int IdEnvio { get; set; }

    public int Detalle { get; set; }

    public int IdProducto { get; set; }

    public int Cantidad { get; set; }

    public string Comentario { get; set; }

    [JsonIgnore]
    public virtual Envio IdEnvioNavigation { get; set; }
   
    public virtual Producto IdProductoNavigation { get; set; }
}