// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models;

public partial class Envio
{
    public int Id { get; set; }

    public DateTime Fecha { get; set; }

    public string DniCliente { get; set; }

    public string Direccion { get; set; }

    public string PalabraSecreta { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<DetallesEnvio> TDetallesEnvios { get; set; } = new List<DetallesEnvio>();
}