// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApi.Models;

public partial class EnviosDBContext : DbContext
{
    public EnviosDBContext(DbContextOptions<EnviosDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DetallesEnvio> TDetallesEnvios { get; set; }

    public virtual DbSet<Envio> TEnvios { get; set; }

    public virtual DbSet<Producto> TProductos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DetallesEnvio>(entity =>
        {
            entity.HasKey(e => new { e.IdEnvio, e.Detalle });

            entity.ToTable("T_Detalles_Envio");

            entity.Property(e => e.IdEnvio).HasColumnName("id_envio");
            entity.Property(e => e.Detalle).HasColumnName("detalle");
            entity.Property(e => e.Cantidad)
                .HasDefaultValueSql("((1))")
                .HasColumnName("cantidad");
            entity.Property(e => e.Comentario)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("comentario");
            entity.Property(e => e.IdProducto).HasColumnName("id_producto");

            entity.HasOne(d => d.IdEnvioNavigation).WithMany(p => p.TDetallesEnvios)
                .HasForeignKey(d => d.IdEnvio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_T_Detalles_Envio_T_Envios");

            entity.HasOne(d => d.IdProductoNavigation).WithMany(p => p.TDetallesEnvios)
                .HasForeignKey(d => d.IdProducto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_T_Detalles_Envio_T_Productos");
        });

        modelBuilder.Entity<Envio>(entity =>
        {
            entity.ToTable("T_Envios");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Direccion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("direccion");
            entity.Property(e => e.DniCliente)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("dniCliente");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValueSql("('En preparación')")
                .HasColumnName("estado");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.PalabraSecreta)
                .IsRequired()
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("palabraSecreta");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.IdProducto);

            entity.ToTable("T_Productos");

            entity.Property(e => e.IdProducto).HasColumnName("id_producto");
            entity.Property(e => e.NProducto)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("n_producto");
            entity.Property(e => e.Precio).HasColumnName("precio");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}