// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApi.Models;

public partial class Producto
{
    public int IdProducto { get; set; }

    public string NProducto { get; set; }

    public double Precio { get; set; }
    [JsonIgnore]
    public virtual ICollection<DetallesEnvio> TDetallesEnvios { get; set; } = new List<DetallesEnvio>();
}